version: "3"
services:
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    # container_name: elasticsearch
    ports:
      - 5000-5100:9200
networks:
  default:
    name: elasticsearch

volumes:
  elasticsearch-data:
    driver: local