version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
          
  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - 16379:8001

networks:
  default:
    name: redis-network

volumes:
  redis-data:
    driver: local
